INSERT INTO `#__annotations` (`annotation_id`, `page`, `selector`, `position`, `text`, `ordering`) VALUES
(1, 'administrator/extensions/modules?application=site', 'body#minwidth-body div#container div#content-box form.-koowa-grid div.scrolling_outer table.adminlist thead tr th a @1', 'left', 'Lorem ipsum dolor sit amet', 8),
(2, 'administrator/users', 'body#minwidth-body div#container div#toolbar-box div @1', 'left', '<p><img src="http://localhost/scrap/clippy.png" style="float:right" />It appears you are trying to wreck the DOM like never before. Would you like to:<br /><ul><li><a href="#">Seek professional help?</a></li><li><a href="#">RTFM?</a></li><li><a href="#">STFU?</a></li></ul></p>', 7),
(6, 'administrator/users', 'body#minwidth-body div#container div#toolbar-box div#toolbar-users table.toolbar tbody tr td#toolbar-logout a @0', 'top', 'Bla bla bla<br /><strong>test</strong>', 4),
(3, 'administrator/index.php?option=com_dashboard&view=dashboard', 'body#minwidth-body div#debug dl#tabs-debug dt @4', 'right', 'Take a look at the text translations!', 6),
(5, 'administrator/annotations?layout=default&page=administrator/annotations?layout=default&page=administrator/extensions/modules?', 'body#minwidth-body div#container div#header-box ul#menu li.node ul li a @1', 'bottom', 'Lorem ipsum dolor sit amet', 3),
(4, 'administrator/annotations?layout=default&page=administrator/extensions/modules?application=site', 'body#minwidth-body div#container div#toolbar-box div @1', 'bottom', 'Way to go!', 5),
(7, 'administrator/settings', '#settings[system][smtpauth]1', 'right', 'Works perfectly with GMail SMTP!', 1),
(8, 'administrator/index.php?option=com_dashboard&view=dashboard', 'body#minwidth-body div#debug dl#tabs-debug dt.icon span @2', 'bottom', 'Analyse the database queries.', 2);
